### PR TITLE
Document what defaults are ok for dictionary values.

### PR DESCRIPTION
**Pull request by jyasskin**
***
<a href="https://whatpr.org/webidl/1215.html" title="Last updated on Oct 13, 2022, 5:14 AM UTC (9996240)">Preview</a> | <a href="https://whatpr.org/webidl/1215/e3d0c74...9996240.html" title="Last updated on Oct 13, 2022, 5:14 AM UTC (9996240)">Diff</a>

### CODE REVIEW

**Comment by domenic** [comment]
This is kind of messy since the section you're modifying is defining the concept of default value, whereas the thing you're referencing is the grammar production for how default values manifest in the syntax. The syntax is discussed below already:

> If the identifier is followed by a U+003D EQUALS SIGN ("=") and a value (matching [DefaultValue](https://whatpr.org/webidl/1215.html#prod-DefaultValue)), then that gives the dictionary member its [default value](https://whatpr.org/webidl/1215.html#dfn-dictionary-member-default-value).

I assume you're doing this because the existing text was not clear to someone, so that probably means we should try to make default values clearer in some way, but I'm hesitant to do so by duplicating the "what is a default value's syntax" parts of the spec into the semantics parts.

**Comment by jyasskin** [comment]
Yep, I couldn't find the place that said what defaults were possible without reading the whole dictionaries section. Thanks for pointing it out. This isn't a problem for [optional arguments](https://webidl.spec.whatwg.org/#dfn-optional-argument-default-value), which don't try to separate their syntax from their semantics. Dictionaries don't really have a separation between syntax and semantics either, so I'd be inclined to move the whole definition of default values down to the place that says what their values can be. Here's that patch in case you agree.

**Comment by domenic** [comment]
I suspect I am happy with this, but PR preview is broken because Bikeshed. And that is also breaking the build. So, we'll revisit this at some point...

**Review by domenic — APPROVED** [review]
Nice, now that I can see the preview, this looks like a nice improvement.

**Pull request merged**
